// <auto-generated />
using System;
using Dms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260919083714_delete_table_noidungthidau")]
    partial class delete_table_noidungthidau
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dms.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThuKyId")
                        .HasColumnType("int");

                    b.Property<int?>("TrongTaiId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("ThuKyId");

                    b.HasIndex("TrongTaiId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Dms.Domain.Entities.BangDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaiDauMonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDauMonTheThaoId");

                    b.ToTable("BangDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.CauHinhLichThiDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CaChieuBatDau")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CaChieuKetThuc")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CaSangBatDau")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CaSangKetThuc")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CaToBatDau")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CaToKetThuc")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("ChiaCaThiDau")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KhoangCachGiuaCacVongGio")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MoiVongMotNgay")
                        .HasColumnType("bit");

                    b.Property<int>("MonTheThaoId")
                        .HasColumnType("int");

                    b.Property<int>("NghiToiThieuGiua2TranPhut")
                        .HasColumnType("int");

                    b.Property<int>("NghiToiThieuTrongTaiPhut")
                        .HasColumnType("int");

                    b.Property<int>("SoHiepDauMacDinh")
                        .HasColumnType("int");

                    b.Property<int>("SoTranToiDaMoiDoiMoiNgay")
                        .HasColumnType("int");

                    b.Property<int>("SoTranToiDaMoiTrongTaiMoiNgay")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianDemDiChuyenPhut")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianDemDonSanPhut")
                        .HasColumnType("int");

                    b.Property<int>("ThoiGianMoiHiepPhut")
                        .HasColumnType("int");

                    b.Property<int>("ThoiLuongTranMacDinhPhut")
                        .HasColumnType("int");

                    b.Property<bool>("UuTienChungKetNgayCuoi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MonTheThaoId")
                        .IsUnique();

                    b.ToTable("CauHinhLichThiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ChiTietDangKyThiDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DangKyThiDauId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoThuTu")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VanDongVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DangKyThiDauId");

                    b.HasIndex("VanDongVienId");

                    b.ToTable("ChiTietDangKyThiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.CumSan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SoLuongSan")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CumSan");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DangKyThiDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoiId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GiaiDauMonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDangKy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangKy")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DoiId");

                    b.HasIndex("GiaiDauMonTheThaoId");

                    b.ToTable("DangKyThiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DanhMucMonTheThao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DanhMucMonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DieuLeGiaiDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaiDauId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDauId");

                    b.ToTable("DieuLeGiaiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DieuLeMonTheThao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonTheThaoId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TepDinhKem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MonTheThaoId");

                    b.ToTable("DieuLeMonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Doi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NguoiQuanLy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("Doi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DonVi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DonViChaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KhoiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDonVi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NguoiDaiDien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonViChaId");

                    b.HasIndex("KhoiId");

                    b.ToTable("DonVi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("HanDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhamVi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.ToTable("GiaiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDauKhoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaiDauId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KhoiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDauId");

                    b.HasIndex("KhoiId");

                    b.ToTable("GiaiDauKhoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDauMonTheThao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaiDauId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDauId");

                    b.HasIndex("MonTheThaoId");

                    b.ToTable("GiaiDauMonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.HiepDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoHiep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TranDauId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TranDauId");

                    b.ToTable("HiepDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.HuyChuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DangKyThiDauId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GiaiDauId")
                        .HasColumnType("int");

                    b.Property<int>("GiaiDauMonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiHuyChuongId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTrao")
                        .HasColumnType("datetime2");

                    b.Property<int>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DangKyThiDauId")
                        .IsUnique();

                    b.HasIndex("GiaiDauId");

                    b.HasIndex("GiaiDauMonTheThaoId");

                    b.HasIndex("LoaiHuyChuongId");

                    b.ToTable("HuyChuong");
                });

            modelBuilder.Entity("Dms.Domain.Entities.KetQuaHiepDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("HiepDauId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThanhPhanTranDauId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HiepDauId");

                    b.HasIndex("ThanhPhanTranDauId");

                    b.ToTable("KetQuaHiepDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.KetQuaTranDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Diem")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQuaText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("KyLuc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiKetQua")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ThanhPhanTranDauId")
                        .HasColumnType("int");

                    b.Property<int?>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThanhPhanTranDauId");

                    b.ToTable("KetQuaTranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Khoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Khoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.LichSuChuyenDoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DoiCuId")
                        .HasColumnType("int");

                    b.Property<int>("DoiMoiId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayChuyen")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiXacNhan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("VanDongVienId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoiCuId");

                    b.HasIndex("DoiMoiId");

                    b.HasIndex("VanDongVienId");

                    b.ToTable("LichSuChuyenDoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.LoaiHuyChuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LoaiHuyChuong");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.MonTheThao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("HinhThucThiDau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaMonDongDoi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SoDoiToiDa")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongVanDongVienToiDa")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongVanDongVienToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucId");

                    b.ToTable("MonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.PhanCongTrongTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TranDauId")
                        .HasColumnType("int");

                    b.Property<int>("TrongTaiId")
                        .HasColumnType("int");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TranDauId");

                    b.HasIndex("TrongTaiId");

                    b.ToTable("PhanCongTrongTai");
                });

            modelBuilder.Entity("Dms.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Dms.Domain.Entities.SanDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CumSanId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiSan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MonTheThaoId")
                        .HasColumnType("int");

                    b.Property<int?>("SoSan")
                        .HasColumnType("int");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CumSanId");

                    b.HasIndex("MonTheThaoId");

                    b.ToTable("SanDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhPhanTranDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DangKyThiDauId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoLane")
                        .HasColumnType("int");

                    b.Property<int?>("ThuTuThiDau")
                        .HasColumnType("int");

                    b.Property<int>("TranDauId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ViTri")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DangKyThiDauId");

                    b.HasIndex("TranDauId");

                    b.ToTable("ThanhPhanTranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhVienBang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BangDauId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DangKyThiDauId")
                        .HasColumnType("int");

                    b.Property<decimal>("Diem")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("DiemBiGhi")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("DiemGhiDuoc")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("HatGiong")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoHoa")
                        .HasColumnType("int");

                    b.Property<int>("SoThang")
                        .HasColumnType("int");

                    b.Property<int>("SoThua")
                        .HasColumnType("int");

                    b.Property<int>("SoTran")
                        .HasColumnType("int");

                    b.Property<int?>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BangDauId");

                    b.HasIndex("DangKyThiDauId");

                    b.ToTable("ThanhVienBang");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhVienDoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoiId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaDoiTruong")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoAo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VanDongVienId")
                        .HasColumnType("int");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DoiId");

                    b.HasIndex("VanDongVienId");

                    b.ToTable("ThanhVienDoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThuKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViCongTac")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ThuKy");
                });

            modelBuilder.Entity("Dms.Domain.Entities.TranDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BangDauId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GiaiDauMonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SanDauId")
                        .HasColumnType("int");

                    b.Property<int>("SoTran")
                        .HasColumnType("int");

                    b.Property<string>("TenTran")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VongDauId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BangDauId");

                    b.HasIndex("GiaiDauMonTheThaoId");

                    b.HasIndex("SanDauId");

                    b.HasIndex("VongDauId");

                    b.ToTable("TranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.TrongTai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CapBac")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TrongTai");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VanDongVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DonViId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonViId");

                    b.ToTable("VanDongVien");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VongDau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaiDauMonTheThaoId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiVong")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiaiDauMonTheThaoId");

                    b.ToTable("VongDau");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Dms.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DonVi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.ThuKy", "ThuKy")
                        .WithMany()
                        .HasForeignKey("ThuKyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.TrongTai", "TrongTai")
                        .WithMany()
                        .HasForeignKey("TrongTaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");

                    b.Navigation("ThuKy");

                    b.Navigation("TrongTai");
                });

            modelBuilder.Entity("Dms.Domain.Entities.BangDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.GiaiDauMonTheThao", "GiaiDauMonTheThao")
                        .WithMany("BangDaus")
                        .HasForeignKey("GiaiDauMonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaiDauMonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.CauHinhLichThiDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.MonTheThao", "MonTheThao")
                        .WithOne("CauHinhLichThiDau")
                        .HasForeignKey("Dms.Domain.Entities.CauHinhLichThiDau", "MonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ChiTietDangKyThiDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DangKyThiDau", "DangKyThiDau")
                        .WithMany("ChiTietDangKyThiDaus")
                        .HasForeignKey("DangKyThiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.VanDongVien", "VanDongVien")
                        .WithMany("ChiTietDangKyThiDaus")
                        .HasForeignKey("VanDongVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyThiDau");

                    b.Navigation("VanDongVien");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DangKyThiDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.Doi", "Doi")
                        .WithMany("DangKyThiDaus")
                        .HasForeignKey("DoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.GiaiDauMonTheThao", "GiaiDauMonTheThao")
                        .WithMany("DangKyThiDaus")
                        .HasForeignKey("GiaiDauMonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doi");

                    b.Navigation("GiaiDauMonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DieuLeGiaiDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.GiaiDau", "GiaiDau")
                        .WithMany("DieuLeGiaiDaus")
                        .HasForeignKey("GiaiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DieuLeMonTheThao", b =>
                {
                    b.HasOne("Dms.Domain.Entities.MonTheThao", "MonTheThao")
                        .WithMany("DieuLeMonTheThaos")
                        .HasForeignKey("MonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Doi", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DonVi", "DonVi")
                        .WithMany("Dois")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DonVi", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DonVi", "DonViCha")
                        .WithMany("DonViCon")
                        .HasForeignKey("DonViChaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.Khoi", "Khoi")
                        .WithMany("DonVis")
                        .HasForeignKey("KhoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonViCha");

                    b.Navigation("Khoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDauKhoi", b =>
                {
                    b.HasOne("Dms.Domain.Entities.GiaiDau", "GiaiDau")
                        .WithMany("GiaiDauKhois")
                        .HasForeignKey("GiaiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.Khoi", "Khoi")
                        .WithMany("GiaiDauKhois")
                        .HasForeignKey("KhoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaiDau");

                    b.Navigation("Khoi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDauMonTheThao", b =>
                {
                    b.HasOne("Dms.Domain.Entities.GiaiDau", "GiaiDau")
                        .WithMany("GiaiDauMonTheThaos")
                        .HasForeignKey("GiaiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.MonTheThao", "MonTheThao")
                        .WithMany("GiaiDauMonTheThaos")
                        .HasForeignKey("MonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaiDau");

                    b.Navigation("MonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.HiepDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.TranDau", "TranDau")
                        .WithMany("HiepDaus")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.HuyChuong", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DangKyThiDau", "DangKyThiDau")
                        .WithOne("HuyChuong")
                        .HasForeignKey("Dms.Domain.Entities.HuyChuong", "DangKyThiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.GiaiDau", "GiaiDau")
                        .WithMany("HuyChuongs")
                        .HasForeignKey("GiaiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.GiaiDauMonTheThao", "GiaiDauMonTheThao")
                        .WithMany("HuyChuongs")
                        .HasForeignKey("GiaiDauMonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.LoaiHuyChuong", "LoaiHuyChuong")
                        .WithMany("HuyChuongs")
                        .HasForeignKey("LoaiHuyChuongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyThiDau");

                    b.Navigation("GiaiDau");

                    b.Navigation("GiaiDauMonTheThao");

                    b.Navigation("LoaiHuyChuong");
                });

            modelBuilder.Entity("Dms.Domain.Entities.KetQuaHiepDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.HiepDau", "HiepDau")
                        .WithMany("KetQuaHiepDaus")
                        .HasForeignKey("HiepDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.ThanhPhanTranDau", "ThanhPhanTranDau")
                        .WithMany("KetQuaHiepDaus")
                        .HasForeignKey("ThanhPhanTranDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HiepDau");

                    b.Navigation("ThanhPhanTranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.KetQuaTranDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.ThanhPhanTranDau", "ThanhPhanTranDau")
                        .WithMany("KetQuaTranDaus")
                        .HasForeignKey("ThanhPhanTranDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThanhPhanTranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.LichSuChuyenDoi", b =>
                {
                    b.HasOne("Dms.Domain.Entities.Doi", "DoiCu")
                        .WithMany()
                        .HasForeignKey("DoiCuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.Doi", "DoiMoi")
                        .WithMany()
                        .HasForeignKey("DoiMoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.VanDongVien", "VanDongVien")
                        .WithMany("LichSuChuyenDois")
                        .HasForeignKey("VanDongVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoiCu");

                    b.Navigation("DoiMoi");

                    b.Navigation("VanDongVien");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Dms.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Dms.Domain.Entities.MonTheThao", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DanhMucMonTheThao", "DanhMuc")
                        .WithMany("MonTheThaos")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("Dms.Domain.Entities.PhanCongTrongTai", b =>
                {
                    b.HasOne("Dms.Domain.Entities.TranDau", "TranDau")
                        .WithMany("PhanCongTrongTais")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.TrongTai", "TrongTai")
                        .WithMany("PhanCongTrongTais")
                        .HasForeignKey("TrongTaiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TranDau");

                    b.Navigation("TrongTai");
                });

            modelBuilder.Entity("Dms.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dms.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dms.Domain.Entities.SanDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.CumSan", "CumSan")
                        .WithMany("SanDaus")
                        .HasForeignKey("CumSanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.MonTheThao", "MonTheThao")
                        .WithMany("SanDaus")
                        .HasForeignKey("MonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CumSan");

                    b.Navigation("MonTheThao");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhPhanTranDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DangKyThiDau", "DangKyThiDau")
                        .WithMany("ThanhPhanTranDaus")
                        .HasForeignKey("DangKyThiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.TranDau", "TranDau")
                        .WithMany("ThanhPhanTranDaus")
                        .HasForeignKey("TranDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DangKyThiDau");

                    b.Navigation("TranDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhVienBang", b =>
                {
                    b.HasOne("Dms.Domain.Entities.BangDau", "BangDau")
                        .WithMany("ThanhVienBangs")
                        .HasForeignKey("BangDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.DangKyThiDau", "DangKyThiDau")
                        .WithMany("ThanhVienBangs")
                        .HasForeignKey("DangKyThiDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BangDau");

                    b.Navigation("DangKyThiDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhVienDoi", b =>
                {
                    b.HasOne("Dms.Domain.Entities.Doi", "Doi")
                        .WithMany("ThanhVienDois")
                        .HasForeignKey("DoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.VanDongVien", "VanDongVien")
                        .WithMany("ThanhVienDois")
                        .HasForeignKey("VanDongVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doi");

                    b.Navigation("VanDongVien");
                });

            modelBuilder.Entity("Dms.Domain.Entities.TranDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.BangDau", "BangDau")
                        .WithMany("TranDaus")
                        .HasForeignKey("BangDauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.GiaiDauMonTheThao", "GiaiDauMonTheThao")
                        .WithMany("TranDaus")
                        .HasForeignKey("GiaiDauMonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.SanDau", "SanDau")
                        .WithMany("TranDaus")
                        .HasForeignKey("SanDauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dms.Domain.Entities.VongDau", "VongDau")
                        .WithMany("TranDaus")
                        .HasForeignKey("VongDauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BangDau");

                    b.Navigation("GiaiDauMonTheThao");

                    b.Navigation("SanDau");

                    b.Navigation("VongDau");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VanDongVien", b =>
                {
                    b.HasOne("Dms.Domain.Entities.DonVi", "DonVi")
                        .WithMany("VanDongViens")
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VongDau", b =>
                {
                    b.HasOne("Dms.Domain.Entities.GiaiDauMonTheThao", "GiaiDauMonTheThao")
                        .WithMany("VongDaus")
                        .HasForeignKey("GiaiDauMonTheThaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaiDauMonTheThao");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Dms.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Dms.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Dms.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dms.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Dms.Domain.Entities.BangDau", b =>
                {
                    b.Navigation("ThanhVienBangs");

                    b.Navigation("TranDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.CumSan", b =>
                {
                    b.Navigation("SanDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DangKyThiDau", b =>
                {
                    b.Navigation("ChiTietDangKyThiDaus");

                    b.Navigation("HuyChuong");

                    b.Navigation("ThanhPhanTranDaus");

                    b.Navigation("ThanhVienBangs");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DanhMucMonTheThao", b =>
                {
                    b.Navigation("MonTheThaos");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Doi", b =>
                {
                    b.Navigation("DangKyThiDaus");

                    b.Navigation("ThanhVienDois");
                });

            modelBuilder.Entity("Dms.Domain.Entities.DonVi", b =>
                {
                    b.Navigation("Dois");

                    b.Navigation("DonViCon");

                    b.Navigation("VanDongViens");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDau", b =>
                {
                    b.Navigation("DieuLeGiaiDaus");

                    b.Navigation("GiaiDauKhois");

                    b.Navigation("GiaiDauMonTheThaos");

                    b.Navigation("HuyChuongs");
                });

            modelBuilder.Entity("Dms.Domain.Entities.GiaiDauMonTheThao", b =>
                {
                    b.Navigation("BangDaus");

                    b.Navigation("DangKyThiDaus");

                    b.Navigation("HuyChuongs");

                    b.Navigation("TranDaus");

                    b.Navigation("VongDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.HiepDau", b =>
                {
                    b.Navigation("KetQuaHiepDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Khoi", b =>
                {
                    b.Navigation("DonVis");

                    b.Navigation("GiaiDauKhois");
                });

            modelBuilder.Entity("Dms.Domain.Entities.LoaiHuyChuong", b =>
                {
                    b.Navigation("HuyChuongs");
                });

            modelBuilder.Entity("Dms.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Dms.Domain.Entities.MonTheThao", b =>
                {
                    b.Navigation("CauHinhLichThiDau");

                    b.Navigation("DieuLeMonTheThaos");

                    b.Navigation("GiaiDauMonTheThaos");

                    b.Navigation("SanDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.SanDau", b =>
                {
                    b.Navigation("TranDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.ThanhPhanTranDau", b =>
                {
                    b.Navigation("KetQuaHiepDaus");

                    b.Navigation("KetQuaTranDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.TranDau", b =>
                {
                    b.Navigation("HiepDaus");

                    b.Navigation("PhanCongTrongTais");

                    b.Navigation("ThanhPhanTranDaus");
                });

            modelBuilder.Entity("Dms.Domain.Entities.TrongTai", b =>
                {
                    b.Navigation("PhanCongTrongTais");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VanDongVien", b =>
                {
                    b.Navigation("ChiTietDangKyThiDaus");

                    b.Navigation("LichSuChuyenDois");

                    b.Navigation("ThanhVienDois");
                });

            modelBuilder.Entity("Dms.Domain.Entities.VongDau", b =>
                {
                    b.Navigation("TranDaus");
                });
#pragma warning restore 612, 618
        }
    }
}
