// <auto-generated />
using Dms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dms.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928075000_AddCauHinhTheThucSchedulingColumns")]
    partial class AddCauHinhTheThucSchedulingColumns
    {
    }
}
